<?php

?>
<div class="right-header">
    <div class="flex-container">
        <div class="left">
            <div class="text-image">
<!--                --><?//= UseImage("images/logo/logo.png", true) ?>
            </div>
            <div class="text-logo">
                <h2>HRIS</h2>
            </div>
        </div>
        <div class="right">
            <div class="buttons">
                <div class="nav-button notif">
                    <div class="icon">
                        <?= UseIcon("bell-thin") ?>
                    </div>
                </div>

                <div class="nav-button profile">
                    <div class="icon">
                        <?= UseIcon("caret-down-thin") ?>
                    </div>
                    <div class="content"></div>
                </div>
            </div>
        </div>
    </div>
</div>