<?php

global $APPLICATION, $PETTYCASH_TABLE_BODY_KEY, $PETTYCASH_TABLE_HEADER_TEXT;

$control = $APPLICATION->FUNCTIONS->PETTYCASH_CONTROL;
$RECORDS = $control->getAllRecords(false);
$ID = "pettycash_id";
$BUTTON = false;

$CREDIT = $control->getPettyCashCredit();
$BALANCE = $control->getBalance();
?>

<?php include "public/views/pages/structures/html_headings.phtml" ?>

<title>Petty Cash</title>

<?php include "public/views/pages/structures/html_heading_closing.phtml" ?>

<?php include "public/views/pages/structures/html_body_open.phtml" ?>

<?php include "public/views/pages/structures/html_opening_parent.phtml" ?>

<div class="left-content">

    <?php include "public/views/pages/structures/html_navbar.phtml" ?>

</div>

<div class="right-content">

    <?php include "public/views/pages/structures/html_right_heading.phtml" ?>

    <div class="right-body">
        <div class="main-body-content-parent">
            <div class="main-body-header">
                <div class="header-nav">
                    <div class="left">
                        <div class="title">
                            <h2>Manage Petty Cash</h2>
                        </div>
                    </div>
                    <div class="right"></div>
                </div>
            </div>
            <div class="main-body-body">
                <div class="data-view-summary-container">
                    <div class="summary-container">
                        <div class="cards-container">
                            <div class="card-container">
                                <div class="title">
                                    <span>Credit</span>
                                </div>
                                <div class="content">
                                    <div class="text">
                                        <span><?= $CREDIT ?></span>
                                    </div>
                                </div>
                            </div>
                            <div class="card-container">
                                <div class="title">
                                    <span>Balance</span>
                                </div>
                                <div class="content">
                                    <div class="text">
                                        <span><?= $BALANCE ?></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="data-table-content">
                    <div class="main-table-container table-component">
                        <div class="main-table-header">
                            <div class="table-header">
                                <div class="left">
                                    <div class="title">
                                        <h2>Petty Cash</h2>
                                    </div>
                                </div>
                                <div class="center">
                                    <div class="search-engine-parent full-width">
                                        <div class="search-engine">
                                            <div class="icon">
                                                <?= UseIcon("magnifying-glass-thin") ?>
                                            </div>
                                            <input type="text" name="search-records" placeholder="Search Records...">
                                        </div>
                                    </div>
                                </div>
                                <div class="right">
                                    <div class="icon-button filter-button">
                                        <div class="icon">
                                            <?= UseIcon("sliders-thin") ?>
                                        </div>
                                        <div class="text">
                                            <span>Filter</span>
                                        </div>
                                    </div>

                                    <div class="icon-button sort-button">
                                        <div class="icon">
                                            <?= UseIcon("arrows-down-up-thin") ?>
                                        </div>
                                        <div class="text">
                                            <span>Sort</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="table-buttons">
                                <div class="left"></div>
                                <div class="right">
                                    <div class="icon-button table-button show-component" data-name="view-request">
                                        <div class="icon">
                                            <?= UseIcon("eye-thin") ?>
                                        </div>
                                        <div class="text">
                                            <span>View</span>
                                        </div>
                                    </div>

                                    <div class="icon-button table-button show-component" data-name="delete-request">
                                        <div class="icon">
                                            <?= UseIcon("trash-thin") ?>
                                        </div>
                                        <div class="text">
                                            <span>Delete</span>
                                        </div>
                                    </div>

                                    <div class="icon-button table-button show-component" data-name="add-request">
                                        <div class="icon">
                                            <?= UseIcon("plus-thin") ?>
                                        </div>
                                        <div class="text">
                                            <span>New</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="main-table-body main-table-requests">
                            <?= CreateTable($PETTYCASH_TABLE_HEADER_TEXT, $PETTYCASH_TABLE_BODY_KEY, $RECORDS, $ID, $BUTTON) ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php include "public/views/pages/structures/html_pipes.phtml" ?>

    <script type="module" src="/public/assets/scripts/pages/main/financial/pettycash.js"></script>

    <?php include "public/views/pages/structures/html_closing_parent.phtml" ?>

    <?php include "public/views/pages/structures/html_body_closing.phtml" ?>
