<?php
global $APPLICATION;

use Application\models\Holiday;

$control = $APPLICATION->FUNCTIONS->HOLIDAY_CONTROL;
$data = json_decode($_POST['data'], true);

/**
 * @type Holiday
 */
$holiday = $control->get($data['id'], true);
?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>View Holiday</h1>
                </div>
                <div class="paragraph">
                    <p>Enter required fields</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Holiday</span>
                            </div>
                            <div class="error-container">
                                <input type="text" name="holiday" placeholder="Holiday" value="<?= $holiday->holiday ?>">
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Date</span>
                            </div>
                            <div class="error-container">
                                <input type="date" name="holiday_date" placeholder="Date" value="<?= $holiday->holiday_date ?>">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group right-side">
                        <div class="form-group">
                            <div class="link clear-form">
                                <span>Clear</span>
                            </div>
                        </div>
                        <div class="form-group filled-green">
                            <input type="submit" value="Add Holiday">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>