<?php

global $APPLICATION;

use Application\controllers\system\UserAuthenticationControl;

$control = new UserAuthenticationControl();

$record = $control->getCurrentUserAuthentication();

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>Set Authentication</h1>
                </div>
                <div class="paragraph">
                    <p>Enter Username and Password</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Req#</span>
                            </div>
                            <div class="error-container">
                                <input type="text" name="username" placeholder="Username" value="<?= $record->username; ?>">
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Remarks</span>
                            </div>
                            <div class="error-container">
                                <input type="text" name="password" placeholder="Password"  value="<?= $record->password; ?>">
                            </div>
                        </div>
                    </div>

                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group">
                        <div class="form-group">
                            <div class="link clear-form">
                                <span>Clear</span>
                            </div>
                        </div>
                        <div class="form-group filled-green">
                            <input type="submit" value="Save">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>