<?php
global $APPLICATION,$POSTED_VALUES;

use Application\models\Pettycash;

$control = $APPLICATION->FUNCTIONS->PETTYCASH_CONTROL;
$data = json_decode($_POST['data'], true);

/**
 * @type pettycash
 */
$pettycash = $control->get($data['id'], true);

$VALUE = ArrayToCombo($POSTED_VALUES);

$ISPOSTED = $pettycash->posted === PostedTypes::POSTED->value;

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>View PettyCash</h1>
                </div>
                <div class="paragraph">
                    <p>Enter required fields</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Name</span>
                            </div>
                            <div class="error-container">
                                <input type="text" name="remarks" placeholder="Remarks" value="<?= $pettycash->remarks ?>">
                            </div>
                        </div>
                    </div>


                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Posted</span>
                            </div>
                            <div class="error-container">
                                <?= CreateComboBox("posted", "Posted", $VALUE, false, $VALUE[$pettycash->posted - 1]) ?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Amount</span>
                            </div>
                            <div class="error-container">
                                <input type="number" name="amount" placeholder="Amount" value="<?= $pettycash->amount ?>">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="popup-footer">
                    <?php if(!$ISPOSTED): ?>
                        <div class="form-group-container submit-group right-side">
                            <div class="form-group">
                                <div class="link clear-form">
                                    <span>Clear</span>
                                </div>
                            </div>
                            <div class="form-group filled-green">
                                <input type="submit" value="Add Cash">
                            </div>
                        </div>
                    <?php endif ?>
                </div>
            </form>
        </div>
    </div>
</div>