<?php
global $APPLICATION, $DEPARTMENTS, $EMPLOYMENT_STATUS, $EMPLOYMENT_TYPES, $EMPLOYMENT_POSITIONS, $RESTDAYS;
global $BENEFICIARIES_TABLE_BODY_KEY, $BENEFICIARIES_TABLE_HEADER_TEXT;

use Application\models\Beneficiary;


$control = $APPLICATION->FUNCTIONS->BENEFICIARY_CONTROL;
$data = json_decode($_POST['data'], true);
/**
 * @type Beneficiary
 */
$beneficiary = $control->get($data['id'], true);
$RECORDS = [];
$ID = -1;
$BUTTON = -1;
?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>View Beneficiary</h1>
                </div>
                <div class="paragraph">
                    <p>Input Informations</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Employee</span>
                            </div>
                            <div class="error-container">
                                <div class="custom-select-box select-employee" data-current="<?= $beneficiary->employee_id ?>">
                                    <div class="main-content">
                                        <input type="text" name="employee" placeholder="Employee" readonly value="<?= $beneficiary->employee->name ?>">

                                        <div class="icon">
                                            <svg width="256px" height="256px" viewBox="0 0 256 256" id="Flat" xmlns="http://www.w3.org/2000/svg">
                                                <path d="M138.82861,130.82861l-80,80a4.00026,4.00026,0,0,1-5.65722-5.65722L130.34326,128,53.17139,50.82861a4.00026,4.00026,0,0,1,5.65722-5.65722l80,80A4.0006,4.0006,0,0,1,138.82861,130.82861Zm80-5.65722-80-80a4.00026,4.00026,0,0,0-5.65722,5.65722L210.34326,128l-77.17187,77.17139a4.00026,4.00026,0,0,0,5.65722,5.65722l80-80A4.0006,4.0006,0,0,0,218.82861,125.17139Z"/>
                                            </svg>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Type</span>
                            </div>
                            <div class="error-container">
                                <?= CreateComboBox("type", "Type", ["A", "B", "C"], false, $beneficiary->type) ?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Name</span>
                            </div>
                            <div class="error-container">
                                <input type="name" name="name" placeholder="Name" value="<?= $beneficiary->name ?>">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group">
                        <div class="form-group">
                            <div class="link clear-form">
                                <span>Clear</span>
                            </div>
                        </div>
                        <div class="form-group filled-green">
                            <input type="submit" value="Save">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>