
<?php

global $APPLICATION;

$DATA = $APPLICATION->GetDashboardData();

$dashboardCards = [
    [
        "title" => "Employees",
        "value" => $DATA['employees']['total'],
    ],
    [
        "title" => "Deployed Employees",
        "value" => $DATA['employees']['deployed'],
    ],
    [
        "title" => "Unemployed Employees",
        "value" => $DATA['employees']['not_deployed'],
    ],
    [
        "title" => "Clients",
        "value" => $DATA['clients']['total'],
    ],
];

$pettyCash = [
    [
        "title" => "Total Credits",
        "value" => "₱". $DATA['petty_cash']['cash'],
    ],
    [
        "title" => "Total Balance",
        "value" => "₱". $DATA['petty_cash']['balance'],
    ],
];

$dataPoints = array_map(function ($record) {
    return ["label" => $record['type'], 'y' => $record['total']];
}, $DATA['expenses']['most_expensive']);
?>

<?php include "public/views/pages/structures/html_headings.phtml" ?>

<title>Dashboard</title>

<?php include "public/views/pages/structures/html_heading_closing.phtml" ?>

<?php include "public/views/pages/structures/html_body_open.phtml" ?>

<?php include "public/views/pages/structures/html_opening_parent.phtml" ?>

<div class="left-content">

<?php include "public/views/pages/structures/html_navbar.phtml" ?>

</div>

<div class="right-content">

<?php include "public/views/pages/structures/html_right_heading.phtml" ?>

<div class="right-body">
    <div class="dashboard-header">
        <div class="header-container">
            <div class="text-container">
                <h1>Good Day, Administrator</h1>
                <p>HRIS Management System</p>
            </div>
        </div>
    </div>
    <div class="dashboard-body">
        <div class="dashboard-grid">
            <div class="left-right">
                <div class="left-grid">
                    <div class="first">
                        <div class="dash-title">
                            <h2>System</h2>
                        </div>
                        <div class="dashboard-cards">
                            <?php foreach ($dashboardCards as $card): ?>
                                <div class="dashboard-card">
                                    <div class="main">
                                        <p><?= $card['title'] ?></p>
                                        <h1><?= $card['value'] ?></h1>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                    <div class="first">
                        <div class="dash-title">
                            <h2>Petty Cash Budget</h2>
                        </div>
                        <div class="dashboard-cards">
                            <?php foreach ($pettyCash as $card): ?>
                                <div class="dashboard-card">
                                    <div class="main">
                                        <p><?= $card['title'] ?></p>
                                        <h1><?= $card['value'] ?></h1>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
                <div class="right-grid">
                    <section>
                        <div class="dash-title">
                            <h2>Average Expenses</h2>
                        </div>
                        <div id="chart-container"></div>
                    </section>
                    <section>
                        <div class="dash-title">
                            <h2>awdwa</h2>
                        </div>
                    </section>
                </div>
            </div>
            <div class="full-grid">
                <div class="min-full-right-grid">
                    <div class="dash-title">
                        <h2>Requisition Drafts</h2>
                    </div>

                    <div class="item-lists">
                        <?php foreach ($DATA['requisitions'] as $requisition): ?>
                            <div class="item">
                                <div class="left-text">
                                    <p><?= implode(", ", array_column((array) $requisition->requisition_info, "particulars")) ?></>
                                </div>
                                <div class="text">
                                    <span>₱<?= $requisition->amount ?></span>

                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
                <div class="half-full-right-grid">
                    <div class="dash-title">
                        <h2>Recent Activities</h2>
                    </div>
                    <div class="item-lists">
                        <?php foreach ($DATA['activities'] as $activity): ?>
                            <div class="item">
                                <div class="left-text">
                                    <p><?= empty($activity->message) ? GetEnumValueOf(array_column(ActivityLogCategories::cases(), "name"), $activity->category) : $activity->message ?></p>
                                </div>
                                <div class="status-text">
                                    <div class="status">
                                        <span><?= GetEnumValueOf(array_column(ActivityLogActionTypes::cases(), "name"), $activity->action) ?></span>
                                    </div>
                                    <div class="status <?= $activity->status == ActivityLogStatus::SUCCESS->value ? 'green' : 'red' ?>">
                                        <span><?= GetEnumValueOf(array_column(ActivityLogStatus::cases(), "name"), $activity->status) ?></span>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="module">
    window.onload = function () {

        var chart = new CanvasJS.Chart("chart-container", {
            animationEnabled: true,
            data: [{
                type: "pie",
                showInLegend: "true",
                legendText: "{label}",
                indexLabelFontSize: 12,
                indexLabel: "{label} - #percent%",
                yValueFormatString: "₱#,##0",
                dataPoints: <?php echo json_encode($dataPoints, JSON_NUMERIC_CHECK); ?>
            }]
        });

        chart.render();

        const credits = document.querySelectorAll('.canvasjs-chart-credit');

        credits.forEach((c) => c.remove())

        document.documentElement.addEventListener("resize", function () {
            const credits = document.querySelectorAll('.canvasjs-chart-credit');

            credits.forEach((c) => c.remove())
        })
    }


</script>
<?php include "public/views/pages/structures/html_pipes.phtml" ?>

<!--<script type="module" src="/public/assets/scripts/pages/main/dashboard.js"></script>-->
<script type="module" src="/public/assets/scripts/libraries/canvasjs/canvasjs-chart-3.8.2/canvasjs.min.js"></script>

<?php include "public/views/pages/structures/html_closing_parent.phtml" ?>

<?php include "public/views/pages/structures/html_body_closing.phtml" ?>
