
<?php include "public/views/pages/structures/html_headings.phtml" ?>

<title>Dashboard</title>

<?php include "public/views/pages/structures/html_heading_closing.phtml" ?>

<?php include "public/views/pages/structures/html_body_open.phtml" ?>

<?php include "public/views/pages/structures/html_opening_parent.phtml" ?>

<div class="left-content">

<?php include "public/views/pages/structures/html_navbar.phtml" ?>

</div>

<div class="right-content">

<?php include "public/views/pages/structures/html_right_heading.phtml" ?>

<div class="right-body">

</div>

<?php include "public/views/pages/structures/html_pipes.phtml" ?>

<!--<script type="module" src="/public/assets/scripts/pages/main/dashboard.js"></script>-->

<?php include "public/views/pages/structures/html_closing_parent.phtml" ?>

<?php include "public/views/pages/structures/html_body_closing.phtml" ?>
