<?php
global $APPLICATION,$ACTIVE_VALUES,$FINISHED_VALUES;

use Application\models\AttendanceGroup;

$control = $APPLICATION->FUNCTIONS->ATTENDANCE_GROUP_CONTROL;
$employeeControl = $APPLICATION->FUNCTIONS->EMPLOYEE_CONTROL;
$data = json_decode($_POST['data'], true);
$id = $data['id'];
/**
 * @type AttendanceGroup
 */
$attendance_group = $control->get($id, true);

$VALUE = ArrayToCombo($ACTIVE_VALUES);
$VALUES = ArrayToCombo($FINISHED_VALUES);
?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-table">
            <div class="popup-top">
                <div class="headline">
                    <h1>Manage Attendance</h1>
                </div>
                <div class="paragraph">
                    <p>Client: <?= $attendance_group->client->name ?></p>
                    <p>Branch: <?= $attendance_group->client->branch ?></p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="client-control">
                        <div class="form-group-container flex">
                            <div class="form-group tooltip">
                                <div class="tooltiptext">
                                    <span>Client</span>
                                </div>
                                <div class="error-container">
                                    <input type="text" name="client_id" placeholder="Client" readonly value="<?= $attendance_group->client->name ?> " disabled>
                                </div>
                            </div>
                            <div class="form-group tooltip">
                                <div class="tooltiptext">
                                    <span>Branch</span>
                                </div>
                                <div class="error-container">
                                    <input type="text" name="branch" placeholder="Branch" disabled value="<?= $attendance_group->client->branch ?>" disabled>
                                </div>
                            </div>
                            <div class="form-group tooltip">
                                <div class="tooltiptext">
                                    <span>Year</span>
                                </div>
                                <div class="error-container">
                                    <input type="text" name="year" placeholder="Year" readonly value="<?= $attendance_group->year ?> " disabled>
                                </div>
                            </div>
                            <div class="form-group tooltip">
                                <div class="tooltiptext">
                                    <span>Period</span>
                                </div>
                                <div class="error-container">
                                    <input type="text" name="period" placeholder="Period" readonly value="<?= $attendance_group->period ?> " disabled>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">

                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Active</span>
                            </div>
                            <label for="" class="min-label">
                                <small><b>Active</b></small>
                            </label>
                            <div class="error-container">
                                <?= CreateComboBox("active", "Active", $VALUE, false, $VALUE[$attendance_group->active - 1]) ?>
                            </div>
                        </div>
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Finished</span>
                            </div>
                            <label for="" class="min-label">
                                <small><b>Finished</b></small>
                            </label>
                            <div class="error-container">
                                <?= CreateComboBox("finished", "Finished", $VALUES, false, $VALUES[$attendance_group->finished - 1]) ?>
                            </div>
                        </div>
                    </div>
                    <div class="employee-control">
                        <div class="employee-attendance-parent main-attendance-table-container">
                            <?php foreach ($attendance_group->client->deployed_employees as $deployed_employee):  ?>

                                <?= CreateEmployeeAttendanceTable($attendance_group, $employeeControl->get($deployed_employee->employment['employee_id'], true)) ?>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group right-side">
                        <div class="form-group filled-green">
                            <input type="submit" value="Save">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>