<?php

global $APPLICATION, $DEPLOYMENT_TABLE_BODY_KEY, $DEPLOYMENT_TABLE_HEADER_TEXT;

$clientControl = $APPLICATION->FUNCTIONS->CLIENT_CONTROL;

$control = $APPLICATION->FUNCTIONS->DEPLOYED_EMPLOYEE_CONTROL;
$RECORDS = $control->getAllRecords(true);
$RECORDS = empty($RECORDS) ? [] : $control->filterRecords(["client_id" => $RECORDS[0]->client_id], false);

$ID = "deployed_employee_id";
$BUTTON = false;

$ALLCLIENTS = $clientControl->getAllRecords(true);
?>

<?php include "public/views/pages/structures/html_headings.phtml" ?>

<title>Assign Employees</title>

<?php include "public/views/pages/structures/html_heading_closing.phtml" ?>

<?php include "public/views/pages/structures/html_body_open.phtml" ?>

<?php include "public/views/pages/structures/html_opening_parent.phtml" ?>

<div class="left-content">

    <?php include "public/views/pages/structures/html_navbar.phtml" ?>

</div>

<div class="right-content">

    <?php include "public/views/pages/structures/html_right_heading.phtml" ?>

    <div class="right-body">
        <div class="main-body-content-parent">
            <div class="main-body-header">
                <div class="header-nav">
                    <div class="left">
                        <div class="title">
                            <h2>Assign Employees</h2>
                        </div>

                    </div>
                    <div class="right"></div>
                </div>
            </div>
            <div class="main-body-body two-flex">
                <div class="data-table-selector">
                    <div class="selector-header">
                        <div class="title">
                            <h2>Clients</h2>
                        </div>
                        <div class="search-engine-parent full-width">
                            <div class="search-engine">
                                <div class="icon">
                                    <?= UseIcon("magnifying-glass-thin") ?>
                                </div>
                                <input type="text" name="search-records" placeholder="Search Records...">
                            </div>
                        </div>
                    </div>
                    <div class="selector-body">
                        <ul class="select-list selection-parent">
                            <?php foreach ($ALLCLIENTS as $client): ?>
                                <li class="item-list" data-id="<?= $client->client_id ?>">
                                    <span><?= $client->name . "   -   " . $client->branch?></span>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
                <div class="data-table-content">
                    <div class="main-table-container table-component">
                        <div class="main-table-header">
                            <div class="table-header">
                                <div class="left">
                                    <div class="title">
                                        <h2>Deployed Employees</h2>
                                    </div>
                                </div>
                                <div class="center">

                                </div>
                                <div class="right">
                                    <div class="icon-button table-button show-component" data-name="view-request">
                                        <div class="icon">
                                            <?= UseIcon("eye-thin") ?>
                                        </div>
                                    </div>

                                    <div class="icon-button table-button show-component" data-name="delete-request">
                                        <div class="icon">
                                            <?= UseIcon("trash-thin") ?>
                                        </div>
                                    </div>

                                    <div class="icon-button table-button show-component" data-name="add-request">
                                        <div class="icon">
                                            <?= UseIcon("plus-thin") ?>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="main-table-body main-table-requests">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php include "public/views/pages/structures/html_pipes.phtml" ?>

    <script type="module" src="/public/assets/scripts/pages/main/client_manager/assign.js"></script>

    <?php include "public/views/pages/structures/html_closing_parent.phtml" ?>

    <?php include "public/views/pages/structures/html_body_closing.phtml" ?>
