<div class="main-list-list">
        <li class="item">
            <div class="icon">

            </div>
            <div class="item-content">
                <div class="left">
                    <div class="text">
                        <span>Your Profile</span>
                    </div>
                </div>
            </div>
        </li>

        <li class="item">
            <div class="icon">

            </div>
            <div class="item-content">
                <div class="left">
                    <div class="text">
                        <span>Settings</span>
                    </div>
                </div>
            </div>
        </li>

    <li class="item">
        <div class="icon">

        </div>
        <div class="item-content">
            <div class="left">
                <div class="text">
                    <span>Logout</span>
                </div>
            </div>
        </div>
    </li>
</div>