<?php
global $APPLICATION,$POSTED_VALUES,$PAID_VALUES;

use Application\models\Adjustment;
$control = $APPLICATION->FUNCTIONS->ADJUSTMENT_CONTROL;
$data = json_decode($_POST['data'], true);

/**
 * @type Adjustment
 */
$adjustment = $control->get($data['id'], true);

$VALUE = ArrayToCombo($POSTED_VALUES);
$VALUES = ArrayToCombo($PAID_VALUES);

$ISPOSTED =  $adjustment->posted !== PostedTypes::POSTED->value;
?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>View Adjustments</h1>
                </div>
                <div class="paragraph">
                    <p>Enter required fields</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">

                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Posted</span>
                            </div>
                            <div class="error-container">
                                <?= CreateComboBox("posted", "Posted", $VALUE, false, $VALUE[$adjustment->posted - 1], $ISPOSTED) ?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Paid</span>
                            </div>
                            <div class="error-container">
                                <?= CreateComboBox("paid", "Paid", $VALUES, false, $VALUES[$adjustment->paid - 1], $ISPOSTED) ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="popup-footer">
                    <?php if ($ISPOSTED): ?>
                        <div class="form-group-container submit-group right-side">
                            <div class="form-group">
                                <div class="link clear-form">
                                    <span>Clear</span>
                                </div>
                            </div>
                            <div class="form-group filled-green">
                                <input type="submit" value="Save Adjustment">
                            </div>
                        </div>
                    <?php endif ?>
                </div>
            </form>
        </div>
    </div>
</div>