<?php
global $APPLICATION;

use Application\models\Bank;

$control = $APPLICATION->FUNCTIONS->BANK_CONTROL;
$data = json_decode($_POST['data'], true);
$id = $data['id'];

/**
 * @type Bank
 */
$bank = $control->get($id, true);

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>New Bank</h1>
                </div>
                <div class="paragraph">
                    <p>Enter required fields</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Name</span>
                            </div>
                            <div class="error-container">
                                <input type="text" name="name" placeholder="Name" value="<?= $bank->name ?>">
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Branch</span>
                            </div>
                            <div class="error-container">
                                <input type="text" name="branch" placeholder="Branch" value="<?= $bank->branch ?>">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group right-side">
                        <div class="form-group">
                            <div class="link clear-form">
                                <span>Clear</span>
                            </div>
                        </div>
                        <div class="form-group filled-green">
                            <input type="submit" value="Save Bank">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>