<?php
global $APPLICATION,$POSTED_VALUES,$CANCELLED_VALUES;

use Application\models\Disbursement;

$control = $APPLICATION->FUNCTIONS->DISBURSEMENT_CONTROL;
$data = json_decode($_POST['data'], true);

/**
 * @type Disbursement
 */
$disbursement = $control->get($data['id'], true);

$VALUE = ArrayToCombo($POSTED_VALUES);
$VALUES = ArrayToCombo($CANCELLED_VALUES);

$ISPOSTED = $disbursement->posted === PostedTypes::POSTED->value;
?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>View Disbursement</h1>
                </div>
                <div class="paragraph">
                    <p>Enter required fields</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">

                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Posted</span>
                            </div>
                            <div class="error-container">
                                <?= CreateComboBox("posted", "Posted", $VALUE, false, $VALUE[$disbursement->posted - 1]) ?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Cancelled</span>
                            </div>
                            <div class="error-container">
                                <?= CreateComboBox("cancelled", "Cancelled", $VALUES, false, $VALUES[$disbursement->cancelled - 1]) ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="popup-footer">
                    <?php if(!$ISPOSTED): ?>
                        <div class="form-group-container submit-group right-side">
                            <div class="form-group">
                                <div class="link clear-form">
                                    <span>Clear</span>
                                </div>
                            </div>
                            <div class="form-group filled-green">
                                <input type="submit" value="Save Disbursement">
                            </div>
                        </div>
                    <?php endif ?>

                </div>
            </form>
        </div>
    </div>
</div>