<?php

global $APPLICATION, $REQUISITION_EXPENSES_LESS_TABLE_BODY_KEY, $REQUISITION_EXPENSES_LESS_TABLE_HEADER_TEXT;

$control = $APPLICATION->FUNCTIONS->REQUISITION_CONTROL;
$RECORDS = [];
$ID = -1;
$BUTTON = -1;
?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-table">
            <div class="popup-top">
                <div class="headline">
                    <h1>New Requisition</h1>
                </div>
                <div class="paragraph">
                    <p>List Requisition</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Req#</span>
                            </div>
                            <div class="error-container">
                                <input type="text" name="req_id" placeholder="Request Number" value="<?= $control->generateRequisitionID(); ?>" stillcount="true">
                            </div>
                        </div>
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Remarks</span>
                            </div>
                            <div class="error-container">
                                <input type="text" name="remarks" placeholder="Remarks" >
                            </div>
                        </div>
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Paid To</span>
                            </div>
                            <div class="error-container">
                                <input type="text" name="remarks" placeholder="Paid To" >
                            </div>
                        </div>
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Status</span>
                            </div>
                            <div class="error-container">
                                <input type="text" name="status" placeholder="Status"  value="DRAFT" disabled>
                            </div>
                        </div>
                    </div>

                    <div class="data-table-content">
                        <div class="main-table-container table-component full">
                            <div class="main-table-header">
                                <div class="table-header">
                                    <div class="left">
                                        <div class="title">
                                            <h2>Requisition</h2>
                                        </div>
                                    </div>
                                    <div class="center"></div>
                                    <div class="right"></div>
                                </div>
                                <div class="table-buttons">
                                    <div class="left"></div>
                                    <div class="right">
                                        <div class="icon-button table-button show-component" data-name="delete-request">
                                            <div class="icon">
                                                <?= UseIcon("trash-thin") ?>
                                            </div>
                                        </div>

                                        <div class="icon-button table-button show-component" data-name="add-request">
                                            <div class="icon">
                                                <?= UseIcon("plus-thin") ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="main-table-body main-table-requests">
                                <?= CreateTable($REQUISITION_EXPENSES_LESS_TABLE_HEADER_TEXT, $REQUISITION_EXPENSES_LESS_TABLE_BODY_KEY, $RECORDS, $ID, $BUTTON) ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group">
                        <div class="form-group">
                            <div class="link clear-form">
                                <span>Clear</span>
                            </div>
                        </div>
                        <div class="form-group filled-green">
                            <input type="submit" value="Save">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>