<?php

global $APPLICATION, $VAT_VALUES ,$BASIC_VALUES;
global $REQUISITION_EXPENSES_LESS_TABLE_BODY_KEY, $REQUISITION_EXPENSES_LESS_TABLE_HEADER_TEXT;

$RECORDS = [];
$ID = -1;
$BUTTON = -1;
?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>New Requisition</h1>
                </div>
                <div class="paragraph">
                    <p>Input Information</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="form-group-container flex">

                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Vat / Non Vat</span>
                            </div>
                            <div class="error-container">
                                <?= CreateComboBox("vat_non_vat", "Vat / Non Vat", [["text" => "Vat", "value" => true], ["text" => "Non Vat", "value" => false]]) ?>

                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Type</span>
                            </div>
                            <div class="error-container">
                                <?= CreateComboBox("type", "Type", $VAT_VALUES) ?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Particulars</span>
                            </div>
                            <div class="error-container">
                                <textarea name="particulars" class="small"  cols="30" rows="10" placeholder="Particulars"></textarea>
                            </div>
                        </div>
                    </div>


                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Basic Unit</span>
                            </div>
                            <div class="error-container">
                                <?= CreateComboBox("basic_unit", "Basic Unit", $BASIC_VALUES) ?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Quantity</span>
                            </div>
                            <div class="error-container">
                                <input type="number" name="quantity" placeholder="Quantity">
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Unit Price</span>
                            </div>
                            <div class="error-container">
                                <input type="number" name="unit_price" placeholder="Unit Price">
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Amount</span>
                            </div>
                            <div class="error-container">
                                <input type="number" name="amount" placeholder="Amount" readonly>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group">
                        <div class="form-group">
                            <div class="link clear-form">
                                <span>Clear</span>
                            </div>
                        </div>
                        <div class="form-group filled-green">
                            <input type="submit" value="Save">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>