<?php

global $APPLICATION, $NETPAYS_TABLE_BODY_KEY, $NETPAYS_TABLE_HEADER_TEXT;

$employeeControl = $APPLICATION->FUNCTIONS->EMPLOYEE_CONTROL;
$clientControl = $APPLICATION->FUNCTIONS->CLIENT_CONTROL;
$control = $APPLICATION->FUNCTIONS->DEPLOYED_EMPLOYEE_CONTROL;
$RECORDS = [];
$RECORDS = empty($RECORDS) ? [] : $control->filterRecords(["client_id" => $RECORDS[0]->client_id], false);

$ID = "neypay_id";
$BUTTON = false;

$ALLEMPLOYEES = $employeeControl->getAllRecords(true);
?>

<?php include "public/views/pages/structures/html_headings.phtml" ?>

<title>Employee Account</title>

<?php include "public/views/pages/structures/html_heading_closing.phtml" ?>

<?php include "public/views/pages/structures/html_body_open.phtml" ?>

<?php include "public/views/pages/structures/html_opening_parent.phtml" ?>

<div class="left-content">

    <?php include "public/views/pages/structures/html_navbar.phtml" ?>

</div>

<div class="right-content">

    <?php include "public/views/pages/structures/html_right_heading.phtml" ?>

    <div class="right-body">
        <div class="main-body-content-parent">
            <div class="main-body-header">
                <div class="header-nav">
                    <div class="left">
                        <div class="title">
                            <h2>Manage Clients</h2>
                        </div>
                    </div>
                    <div class="right"></div>
                </div>
            </div>
            <div class="main-body-body two-flex">
                <div class="data-table-selector">
                    <div class="selector-header">
                        <div class="title">
                            <h2>Employees</h2>
                        </div>
                        <div class="content-flex">
                            <div class="search-engine-parent full-width">
                                <div class="search-engine">
                                    <div class="icon">
                                        <?= UseIcon("magnifying-glass-thin") ?>
                                    </div>
                                    <input type="text" name="search-records" placeholder="Search Records...">
                                </div>
                            </div>
                            <div class="form-group tooltip">
                                <div class="tooltiptext">
                                    <span>Year</span>
                                </div>
                                <div class="error-container">
                                    <?= CreateComboBox("year", "Year", GetYearsFrom(1990)) ?>
                                </div>
                            </div>
                            <div class="form-group tooltip">
                                <div class="tooltiptext">
                                    <span>Period</span>
                                </div>
                                <div class="error-container">
                                    <?= CreateComboBox("period", "Period", [], false) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="selector-body">
                        <ul class="select-list selection-parent">
                            <?php foreach ($ALLEMPLOYEES as $employee): ?>
                                <li class="item-list" data-id="<?= $employee->employee_id ?>">
                                    <span><?= $employee->name ?></span>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
                <div class="data-table-content">
                    <div class="main-table-container table-component">
                        <div class="main-table-header">
                            <div class="table-header">
                                <div class="left">
                                    <div class="title">
                                        <h2>NET PAYS</h2>
                                    </div>
                                </div>
                                <div class="center">

                                </div>
                                <div class="right">
                                    <div class="icon-button table-button show-component" data-name="view-request">
                                        <div class="icon">
                                            <?= UseIcon("eye-thin") ?>
                                        </div>
                                    </div>

                                    <div class="icon-button table-button show-component" data-name="delete-request">
                                        <div class="icon">
                                            <?= UseIcon("trash-thin") ?>
                                        </div>
                                    </div>

                                    <div class="icon-button table-button show-component" data-name="add-request">
                                        <div class="icon">
                                            <?= UseIcon("plus-thin") ?>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="main-table-body main-table-requests">
                            <?= CreateTable($NETPAYS_TABLE_HEADER_TEXT, $NETPAYS_TABLE_BODY_KEY, $RECORDS, $ID, $BUTTON) ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php include "public/views/pages/structures/html_pipes.phtml" ?>

<!--    <script type="module" src="/public/assets/scripts/pages/main/client_manager/assign.js"></script>-->

    <?php include "public/views/pages/structures/html_closing_parent.phtml" ?>

    <?php include "public/views/pages/structures/html_body_closing.phtml" ?>
