<?php

global $APPLICATION, $MORTUARY_TABLE_BODY_KEY, $MORTUARY_TABLE_HEADER_TEXT;

$control = $APPLICATION->FUNCTIONS->MORTUARY_CONTROL;
$RECORDS = $control->getAllRecords(false);
$ID = "mortuary_id";
$BUTTON = false;
?>

<?php include "public/views/pages/structures/html_headings.phtml" ?>

<title>Mortuary</title>

<?php include "public/views/pages/structures/html_heading_closing.phtml" ?>

<?php include "public/views/pages/structures/html_body_open.phtml" ?>

<?php include "public/views/pages/structures/html_opening_parent.phtml" ?>

<div class="left-content">

    <?php include "public/views/pages/structures/html_navbar.phtml" ?>

</div>

<div class="right-content">

    <?php include "public/views/pages/structures/html_right_heading.phtml" ?>

    <div class="right-body">
        <div class="main-body-content-parent">
            <div class="main-body-header">
                <div class="header-nav">
                    <div class="left">
                        <div class="title">
                            <h2>Manage Mortuary</h2>
                        </div>
                    </div>
                    <div class="right"></div>
                </div>
            </div>
            <div class="main-body-body">
                <div class="data-table-content">
                    <div class="main-table-container table-component">
                        <div class="main-table-header">
                            <div class="table-header">
                                <div class="left">
                                    <div class="title">
                                        <h2>Mortuary</h2>
                                    </div>
                                </div>
                                <div class="center">

                                </div>
                                <div class="right">
                                    <div class="icon-button filter-button">
                                        <div class="icon">
                                            <?= UseIcon("sliders-thin") ?>
                                        </div>
                                        <div class="text">
                                            <span>Filter</span>
                                        </div>
                                    </div>

                                    <div class="icon-button sort-button">
                                        <div class="icon">
                                            <?= UseIcon("arrows-down-up-thin") ?>
                                        </div>
                                        <div class="text">
                                            <span>Sort</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="table-buttons">
                                <div class="left">
                                    <div class="content-flex year-period">
                                        <div class="form-group tooltip">
                                            <div class="tooltiptext">
                                                <span>Year</span>
                                            </div>
                                            <div class="error-container">
                                                <?= CreateComboBox("year", "Year", GetYearsFrom(1990)) ?>
                                            </div>
                                        </div>
                                        <div class="form-group tooltip">
                                            <div class="tooltiptext">
                                                <span>Period</span>
                                            </div>
                                            <div class="error-container">
                                                <?= CreateComboBox("period", "Period", []) ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="right">
                                    <div class="icon-button table-button show-component" data-name="view-request">
                                        <div class="icon">
                                            <?= UseIcon("eye-thin") ?>
                                        </div>
                                        <div class="text">
                                            <span>View</span>
                                        </div>
                                    </div>

                                    <div class="icon-button table-button show-component" data-name="delete-request">
                                        <div class="icon">
                                            <?= UseIcon("trash-thin") ?>
                                        </div>
                                        <div class="text">
                                            <span>Delete</span>
                                        </div>
                                    </div>

                                    <div class="icon-button table-button show-component" data-name="add-request">
                                        <div class="icon">
                                            <?= UseIcon("plus-thin") ?>
                                        </div>
                                        <div class="text">
                                            <span>New</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="main-table-body main-table-requests">
                            <?= CreateTable($MORTUARY_TABLE_HEADER_TEXT, $MORTUARY_TABLE_BODY_KEY, $RECORDS, $ID, $BUTTON) ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php include "public/views/pages/structures/html_pipes.phtml" ?>

        <script type="module" src="/public/assets/scripts/pages/main/personnel/mortuary.js"></script>

    <?php include "public/views/pages/structures/html_closing_parent.phtml" ?>

    <?php include "public/views/pages/structures/html_body_closing.phtml" ?>
