<?php

global $APPLICATION, $LOAN_TABLE_BODY_TEXT, $LOAN_TABLE_HEADER_TEXT;

$control = $APPLICATION->FUNCTIONS->LOAN_CONTROL;
$employControl = $APPLICATION->FUNCTIONS->EMPLOYEE_CONTROL;
$RECORDS = $control->filterRecords(["status" => 1],false);
$ID = "loan_id";
$BUTTON = false;

$data = json_decode($_POST['data'], true);
$id = $data['id'];
//
$employee = $employControl->get($id, true);


?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-table">
            <div class="popup-top">
                <div class="headline">
                    <h1>Select Loans</h1>
                </div>
                <div class="paragraph">
                    <p>You can select multiple loans</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="data-table-content ">
                        <div class="main-table-container items-component full">
                            <div class="main-table-header">
                                <div class="table-header">
                                    <div class="left">
                                        <div class="title">
<!--                                            <h2>All Unpaid Loans of --><?php //= $employee->name ?><!--</h2>-->
                                        </div>
                                    </div>
                                    <div class="center">
                                        <div class="search-engine-parent full-width">
                                            <div class="search-engine">
                                                <div class="icon">
                                                    <?= UseIcon("magnifying-glass-thin") ?>
                                                </div>
                                                <input type="text" name="search-records" placeholder="Search Records...">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="right"></div>
                                </div>
                                <div class="table-buttons">
                                    <div class="left"></div>
                                    <div class="right">
                                        <div class="icon-button table-button show-component" data-name="select-request">
                                            <div class="icon">
                                                <?= UseIcon("eye-thin") ?>
                                            </div>
                                            <div class="text">
                                                <span>Select Loans</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="main-table-body main-table-requests">
                                    <?= CreateTable($LOAN_TABLE_HEADER_TEXT, $LOAN_TABLE_BODY_TEXT, $RECORDS, $ID, $BUTTON) ?>
                                </div>
                            </div>
                        </div>
                    </div>

            </form>
        </div>
    </div>
</div>