<?php
global $APPLICATION;


?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-table go-large">
            <div class="popup-top">
                <div class="headline">
                    <h1>Loan Manager</h1>
                </div>
                <div class="paragraph">
                    <p>Manage loans</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <?php include_once "public/views/components/containers/loan_manager/manager.phtml"?>
                </div>
                <div class="popup-footer">

                </div>
            </form>
        </div>
    </div>
</div>