<?php
global $APPLICATION;

$control = $APPLICATION->FUNCTIONS->BANK_CONTROL;
$banks = $control->getAllRecords(false);

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>New Bank Account</h1>
                </div>

                <div class="paragraph">
                    <p>Please fill up information</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Bank</span>
                            </div>
                            <div class="error-container">
                                <?= CreateComboBox("bank_id", "Bank", ObjectToCombo("name", "bank_id", $banks)) ?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Bank Account #</span>
                            </div>
                            <div class="error-container">
                                <input type="text" name="account_number" placeholder="Bank Account #" >
                            </div>
                        </div>
                    </div>
                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group">
                        <div class="form-group">
                            <div class="link clear-form">
                                <span>Clear</span>
                            </div>
                        </div>
                        <div class="form-group filled-green">
                            <input type="submit" value="Add Bank Account">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>