<?php
global $APPLICATION;

$control = $APPLICATION->FUNCTIONS->BANK_ACCOUNT_CONTROL;
$data = json_decode($_POST['data'], true);

$bank = is_array($data['bank']) ? $data['bank'] : $control->get($data['bank'], true);

$bankControl = $APPLICATION->FUNCTIONS->BANK_CONTROL;
$banks = $bankControl->getAllRecords(false);

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>New Bank Account</h1>
                </div>

                <div class="paragraph">
                    <p>Please fill up information</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Bank</span>
                            </div>
                            <div class="error-container">

        <?= CreateComboBox("bank_id", "Bank", ObjectToCombo("name", "bank_id", $banks), false, [
                                    "text" => !is_array($data['bank']) ? $bank->bank->name :   $bank['bank']['name'],
                                    "value" => !is_array($data['bank']) ? $bank->bank_id :  $bank['bank']['bank_id']
                                ])
        ?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Bank Account #</span>
                            </div>
                            <div class="error-container">
                                <input type="text" name="account_number" placeholder="Bank Account #" value="<?= !is_array($data['bank']) ? $bank->account_number : $bank['account_number'] ?>" >
                            </div>
                        </div>
                    </div>
                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group">
                        <div class="form-group">
                            <div class="link clear-form">
                                <span>Clear</span>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="link delete-form">
                                <span>Delete</span>
                            </div>
                        </div>
                        <div class="form-group filled-green">
                            <input type="submit" value="Save">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>