<?php

global $APPLICATION, $HOLIDAYS_TABLE_HEADER_TEXT, $HOLIDAYS_TABLE_BODY_KEY;

$control = $APPLICATION->FUNCTIONS->HOLIDAY_CONTROL;
$clientHolidayControl = $APPLICATION->FUNCTIONS->CLIENT_HOLIDAY_CONTROL;
$RECORDS = $control->getAllRecords(false);
$ID = "holiday_id";
$BUTTON = false;

$data = json_decode($_POST['data'], true);
$_id = $data['id'];

$selected = $clientHolidayControl->filterRecords(['client_id' => $_id], false);

$selected = array_map(function ($record) {
    return $record['holiday_id'];
}, $selected);

$RECORDS = array_filter($RECORDS, function ($record) use ($selected) {
    return !in_array($record['holiday_id'], $selected);
});

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-table">
            <div class="popup-top">
                <div class="headline">
                    <h1>Select Holiday</h1>
                </div>
                <div class="paragraph">
                    <p>Select Holidays</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="data-table-content ">
                        <div class="main-table-container items-component full">
                            <div class="main-table-header">
                                <div class="table-header">
                                    <div class="left">
                                        <div class="titele">
                                            <h2>All Holiday</h2>
                                        </div>
                                    </div>
                                    <div class="center">
                                        <div class="search-engine-parent full-width">
                                            <div class="search-engine">
                                                <div class="icon">
                                                    <?= UseIcon("magnifying-glass-thin") ?>
                                                </div>
                                                <input type="text" name="search-records" placeholder="Search Records...">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="right"></div>
                                </div>
                                <div class="table-buttons">
                                    <div class="left"></div>
                                    <div class="right">
                                        <div class="icon-button table-button show-component" data-name="select-request">
                                            <div class="icon">
                                                <?= UseIcon("eye-thin") ?>
                                            </div>
                                            <div class="text">
                                                <span>Select Holiday</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="main-table-body main-table-requests">
                                    <?= CreateTable($HOLIDAYS_TABLE_HEADER_TEXT, $HOLIDAYS_TABLE_BODY_KEY, $RECORDS, $ID, $BUTTON) ?>

                                </div>
                            </div>
                        </div>
                    </div>

            </form>
        </div>
    </div>
</div>