<?php
global $APPLICATION, $CLIENT_HOLIDAY_TABLE_HEADER_TEXT, $CLIENT_HOLIDAY_TABLE_BODY_KEY;

$data = json_decode($_POST['data'], true);
$id = $data["id"];

$control = $APPLICATION->FUNCTIONS->CLIENT_HOLIDAY_CONTROL;
$RECORDS = $control->filterRecords(['client_id' => $id], true);
$ID = "client_holiday_id";

$RECORDS = array_map(function ($record) {
    return [
        "client_holiday_id" => $record->client_holiday_id,
        "holiday" => $record->holiday->holiday,
        "date" => $record->holiday->holiday_date,
    ];
}, $RECORDS);

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-table">
            <div class="popup-top">
                <div class="headline">
                    <h1>Client Holiday</h1>
                </div>
                <div class="paragraph">
                    <p>All client holiday</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <div class="popup-bot">

                <div class="data-table-content">
                    <div class="main-table-container table-component">
                        <div class="main-table-header">
                            <div class="table-header">
                                <div class="left"></div>

                                <div class="center">
                                    <div class="search-engine-parent full-width">
                                        <div class="search-engine">
                                            <div class="icon">
                                                <?= UseIcon("magnifying-glass-thin") ?>
                                            </div>
                                            <input type="text" name="search-records" placeholder="Search Records...">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="table-buttons">
                                <div class="left"></div>
                                <div class="right">
                                    <div class="icon-button table-button show-component" data-name="view-request">
                                        <div class="icon">
                                            <?= UseIcon("eye-thin") ?>
                                        </div>
                                        <div class="text">
                                            <span>View</span>
                                        </div>
                                    </div>

                                    <div class="icon-button table-button show-component" data-name="delete-request">
                                        <div class="icon">
                                            <?= UseIcon("trash-thin") ?>
                                        </div>
                                        <div class="text">
                                            <span>Delete</span>
                                        </div>
                                    </div>

                                    <div class="icon-button table-button show-component" data-name="add-request">
                                        <div class="icon">
                                            <?= UseIcon("plus-thin") ?>
                                        </div>
                                        <div class="text">
                                            <span>New</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="main-table-body main-table-requests">
                            <?= CreateTable($CLIENT_HOLIDAY_TABLE_HEADER_TEXT, $CLIENT_HOLIDAY_TABLE_BODY_KEY, $RECORDS, $ID, -1) ?>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>
</div>