<?php
global $APPLICATION,$REGION_VALUES;

$data = json_decode($_POST['data'], true);
$id = $data['id'];

$control = $APPLICATION->FUNCTIONS->CLIENT_CONTROL;

/**
 * @type Client
 */
$client = $control->get($id, true);

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-table">
            <div class="popup-top">
                <div class="headline">
                    <h1>View Client</h1>
                </div>
                <div class="paragraph">
                    <p>Enter Client Informations</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">

                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Name</span>
                            </div>
                            <div class="error-container">
                                <input type="text" name="name" placeholder="Name" value="<?= $client->name ?>">
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Branch</span>
                            </div>
                            <div class="error-container">
                                <input type="text" name="branch" placeholder="Branch" value="<?= $client->branch ?>" >
                            </div>
                        </div>
                    </div>

                    <div class="custom-accordion">
                        <div class="item active">
                            <div class="head">
                                <div class="text">
                                    <span>Client Information</span>
                                </div>
                            </div>
                            <div class="body">
                                <div class="title">
                                    <h3>Client Information</h3>
                                </div>
                                <div class="form-group-container flex">
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>Region</span>
                                        </div>
                                        <div class="error-container">
                                            <?= CreateComboBox("region", "Region", $REGION_VALUES, false, $client->region) ?>

                                        </div>
                                    </div>

                                </div>

                                <div class="form-group-container flex">

                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>Mobile</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>Mobile</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="tel" name="mobile" placeholder="Mobile" value="<?= $client->mobile ?>">
                                        </div>
                                    </div>
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>Telephone</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>Telephone</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="tel" name="telephone" placeholder="Telephone Number" value="<?= $client->telephone ?>" >
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group-container flex">
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>Email</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>Email</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="email" placeholder="Email" value="<?= $client->email ?>">
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group-container flex">
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>Person</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>Person</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="person" placeholder="Person" value="<?= $client->person ?>">
                                        </div>
                                    </div>
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>W/ Pagibig</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>W/ Pagibig</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="w_pagibig" placeholder="W/ Pagibig" value="<?= $client->w_pagibig ?>">
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group-container flex">
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>Address</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>Address</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="address" name="address" placeholder="Address" value="<?= $client->address ?>">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <div class="head">
                                <div class="text">
                                    <span>Salaries and Wages (Reports)</span>
                                </div>
                            </div>
                            <div class="body">
                                <div class="form-group-container flex">
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>12 Vat</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>12% Vat</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="vat" placeholder="12 Vat" value="<?= $client->vat ?>">
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group-container flex">
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>Sw Fee 1</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>Sw Fee 1</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="swfee_1" placeholder="Sw Fee 1" value="<?= $client->swfee_1 ?>" >
                                        </div>
                                    </div>
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>Sw Fee 2</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>Sw Fee 2</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="swfee_2" placeholder="Sw Fee 2" value="<?= $client->swfee_2 ?>">
                                        </div>
                                    </div>
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>Sw Fee 3</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>1Sw Fee 3</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="swfee_3" placeholder="Sw Fee 3" value="<?= $client->swfee_3 ?>">
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group-container flex">
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>Agency Fee 1</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>Agency Fee 1</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="agency_1" placeholder="Agency Fee 1" value="<?= $client->agency_1 ?>">
                                        </div>
                                    </div>
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>Agency Fee 2</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>Agency Fee 2</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="agency_2" placeholder="Agency Fee 2" value="<?= $client->agency_2 ?>">
                                        </div>
                                    </div>
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>Agency Fee 3</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>Agency Fee 3</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="agency_3" placeholder="Agency Fee 3" value="<?= $client->agency_3 ?>">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <div class="head">
                                <div class="text">
                                    <span>Salaries And Wages</span>
                                </div>
                            </div>
                            <div class="body">
                                <div class="form-group-container flex">
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>Regular</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>Regular</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="regular" placeholder="Regular" value="<?= $client->regular ?>">
                                        </div>
                                    </div>
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>Overtime</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>Overtime</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="overtime" placeholder="Overtime" value="<?= $client->overtime ?>">
                                        </div>
                                    </div>
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>13month</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>13month</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="month" placeholder="13 Month" value="<?= $client->month ?>">
                                        </div>
                                    </div>
                                </div>
                                <div class="title">
                                    <h3>Agency Fee</h3>
                                </div>
                                <div class="form-group-container flex">
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>Regular</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>Regular</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="regular_1" placeholder="Regular" value="<?= $client->regular_1 ?>">
                                        </div>
                                    </div>
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>Overtime</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>Overtime</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="overtime_1" placeholder="Overtime" value="<?= $client->overtime_1 ?>" >
                                        </div>
                                    </div>
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>13month</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>13month</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="month_1" placeholder="13month" value="<?= $client->month_1 ?>" >
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <div class="head">
                                <div class="text">
                                    <span>Rates</span>
                                </div>
                            </div>
                            <div class="body">

                                <div class="form-group-container flex">
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>Regular</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>Regular</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="regular_2" placeholder="Regular" value="<?= $client->regular_2 ?>"  >
                                        </div>
                                    </div>
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>Overtime</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>Overtime</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="overtime_2" placeholder="Overtime" value="<?= $client->overtime_2 ?>" >
                                        </div>
                                    </div>
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>NightDiff</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>NightDiff</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="nightdiff" placeholder="NightDiff" value="<?= $client->nightdiff ?>" >
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group-container flex">
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>SEA</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>SEA</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="sea" placeholder="SEA" value="<?= $client->sea ?>"  >
                                        </div>
                                    </div>
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>COLA</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>COLA</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="cola" placeholder="COLA" value="<?= $client->cola ?>" >
                                        </div>
                                    </div>
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>Leave</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>Leave</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="leave_1" placeholder="Leave" value="<?= $client->leave_1 ?>"  >
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group-container flex">
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>Uniform</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>Uniform</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="uniform" placeholder="Uniform" value="<?= $client->uniform ?>" >
                                        </div>
                                    </div>
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>Allowance</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>Allowance</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="allowance" placeholder="Allowance" value="<?= $client->allowance ?>" >
                                        </div>
                                    </div>
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>Head Guard Allowance</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>Head Guard Allowance</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="head_guard_allowance" placeholder="Head Guard Allowance" value="<?= $client->head_guard_allowance ?>" >
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group-container flex">
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>CTPA</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>CTPA</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="ctpa" placeholder="CTPA" value="<?= $client->ctpa ?>" >
                                        </div>
                                    </div>
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>Legal Holiday</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>Legal Holiday</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="legal_holiday" placeholder="Legal Holiday" value="<?= $client->legal_holiday ?>"  >
                                        </div>
                                    </div>
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>Special Holiday</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>Special Holiday</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="special_holiday" placeholder="Special Holiday" value="<?= $client->special_holiday ?>"  >
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group-container flex">
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>Rest Day</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>Rest Day</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="restday" placeholder="Rest Day" value="<?= $client->restday ?>" >
                                        </div>
                                    </div>
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>Legal Holiday OT</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>Legal Holiday OT</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="legal_holiday_ot" placeholder="Legal Holiday OT"  value="<?= $client->legal_holiday_ot ?>">
                                        </div>
                                    </div>
                                    <div class="form-group tooltip">
                                        <div class="tooltiptext">
                                            <span>Special Holiday OT</span>
                                        </div>
                                        <label for="" class="min-label">
                                            <small><b>Special Holiday OT</b></small>
                                        </label>
                                        <div class="error-container">
                                            <input type="text" name="special_holiday_ot" placeholder="Special Holiday OT" value="<?= $client->special_holiday_ot ?>" >
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="popup-footer right-side-flex">
                    <div class="form-group-container submit-group right-left-side">
                        <div class="left-main-side">
                            <div class="form-group">
                                <div class="text-button ">
                                    <div class="text">
                                        <span>Holidays</span>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="right-main-side">
                            <div class="form-group">
                                <div class="link back-form">
                                    <span>Back</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="link clear-form">
                                    <span>Clear</span>
                                </div>
                            </div>
                            <div class="form-group filled-green">
                                <input type="submit" value="Save Client">
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


